server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
      routes:
        - id: auth
          uri: http://auth-service:8083
          predicates:
            - Path=/auth/**
        - id: food
          uri: http://food-service:8081
          predicates:
            - Path=/api/food/**
        - id: calorie
          uri: http://calorie-service:8082
          predicates:
            - Path=/api/calories/**


security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:3de86d2e1023328329e86895cff71a78}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
