server:
  port: 8081

spring:
  application:
    name: food-service

  # OpenAI
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

  # Kafka Producer
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: jdbc:postgresql://dpg-d1h6frvfte5s739co5mg-a.frankfurt-postgres.render.com:5432/database_ic3y
    driver-class-name: org.postgresql.Driver
    username: database_ic3y_user
    password: WVwbgmdllia2gWatqs9fCFFcm3EUVBsM

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    secret: 3de86d2e1023328329e86895cff71a78
